### PR TITLE
Adding debug options, Adding Databases size info, adding build rpm system"

### PR DESCRIPTION
**Pull request by jmrenouard**
Adding information about databases size.

### CODE REVIEW

**Comment by jmrenouard** [comment]
A simple RPM build system has been added.

sh bui

**Comment by cloos** [comment]
@jmrenouard I think that it don't make sense to display all databases by default. Think about users with hundreds or even thousand of databases. This would make the report output useless. But I think an option to display database informations, which defaults to false, would be ok.

What's the rationale behind the rpm build stuff?
Why do you want to create a rpm package for a simple Perl script?

**Comment by jmrenouard** [comment]
@cloos ok I will add a fix with option --dbstat

rpm is just more simply to deploy on your server and control diffision with Pulp.
http://www.pulpproject.org/

**Comment by jmrenouard** [comment]
option --dbstat is coded.

Rpm can help us to mantain deployed version easily.

**Comment by jmrenouard** [comment]
Ok
All is done.
Issue #79 is fixed.
new option --dbstat activated database statistics.

**Comment by cloos** [comment]
@jmrenouard then maybe you should call build.sh build_rpm.sh because you are just building rpm packages, and for example not deb packages ;-)

**Comment by jmrenouard** [comment]
@cloos you are right for sure !

Next commit, script will be remaned.

Thx

**Comment by jmrenouard** [comment]
Merge done with main stream.

**Comment by jmrenouard** [comment]
What contains this patch : 
1° Adding information on each database if and only if --dbstat option is used.
2° A build directory and a build_rpm.sh script to RPM package mysqltuner + basic_password.txt
3° Bug fix on innodb_buffer_pool_instances messages
4° adding a debugprint fonction activated on with --debug option
5° Adding a get_replication_status sub for replication options analyze.
6° adding a sub for percentage calculation
7° adding 2 subs for mysql request.

Best Regards,

**Comment by jmrenouard** [comment]
@major I want to work around documentation.
Is it possible to merge this pull ?

Thnaks for your anwser.

**Comment by jmrenouard** [comment]
perldoc mysqltuner.pl displays help page.
USAGE.md with perldoc contents have been added.
I used POD::Markdown module and pod2markdown to generate USAGE.md

**Comment by jmrenouard** [comment]
Tests done with several set of innodb_buffer_pool_size and innodb_buffer_pool_instances for issues #77 ans #79 show fix from commit a862f36 is doing the job.

**Pull request merged**
