### PR TITLE
adding --reportfile for file output result

### PR DESCRIPTION
**Pull request by jmrenouard**

### CODE REVIEW

**Comment by major** [comment]
Very good idea.  However, could we auto-enable `--nocolor` when `--reportfile` is specified?  Otherwise I end up with this in the report file:

    [^[[0;31m!!^[[0m] Currently running unsupported MySQL version 10.0.17-MariaDB-wsrep
    [^[[0;32mOK^[[0m] Operating on 64-bit architecture

**Comment by jmrenouard** [comment]
Line 144:
$opt{nocolor} = 1 if defined($reportfile);

Nocolor is activated if reportfile is defined.

**Comment by major** [comment]
clap

**Comment by jmrenouard** [comment]
Nice !
I love your image :)

Merge done !

**Pull request merged**
