### PR TITLE
Adding some extras security checks

### PR DESCRIPTION
**Pull request by jmrenouard**
Hello,

This patch contains:
1° Check for anonymous user.
2° Check if users use "user name" as password and derivated version (lower, upper, capitalized version)
3° Check all passwords based on a basic password file.

This patch can be better in many points:
1° Password list file can be parametrized and changing it on command line
2° Precalculated password md5 for all basics password can help us to speed up password checking.
3° Disable password checking based on list by parameter.

Tell me what you think of this patch.

Best regards,
Jean-Marie

### CODE REVIEW

**Comment by major** [comment]
Nice work here.  Would it be possible to adjust the code so that password checking will fail gracefully if the text file is missing?

**Comment by jmrenouard** [comment]
Hi,
Thanks for your response.

When basic password file doesn't exists, the following message is displayed !
[!!] There is not basic password file list !

Then, diagnostic continues !

Is it ok for you ?
BR
Jean-Marie Renouard

**Comment by major** [comment]
Ah, good point.  I missed that. ;)

**Comment by jmrenouard** [comment]
Quick and easy !
BR

**Comment by centminmod** [comment]
why not cracklib http://www.cyberciti.biz/security/linux-password-strength-checker/ ?

**Pull request merged**
